#!/usr/bin/env bash

protoc=$(which protoc)
$protoc --version

# Legacy ratelimit proto
protoc --go_out=plugins=grpc:. proto/ratelimit/*.proto

# Data-plane-api proto
data_plane_cmd="protoc --go_out=plugins=grpc,Menvoy/api/v2/ratelimit/ratelimit.proto=github.com/lyft/ratelimit/proto/envoy/api/v2/ratelimit:proto/. --proto_path=vendor/github.com/envoyproxy/data-plane-api --proto_path=vendor/github.com/lyft/protoc-gen-validate --proto_path=vendor/github.com/google/protobuf/src --proto_path=proto/atlassian_extensions  "
    # ${data_plane_cmd} vendor/github.com/envoyproxy/data-plane-api/envoy/service/ratelimit/v2/rls.proto
${data_plane_cmd} vendor/github.com/envoyproxy/data-plane-api/envoy/api/v2/ratelimit/ratelimit.proto

${data_plane_cmd} proto/atlassian_extensions/custom_rls.proto
# protoc --go_out=plugins=grpc:proto/envoy/service/ratelimit/v2/ rls.proto
mv proto/custom_rls.pb.go proto/envoy/service/ratelimit/v2/rls.pb.go
